const callsInfo = [
  {
    id: 1,
    name: "Fatouma Ali Doualeh",
    text: "Today,",
    time: "15:42",
    imagePath: require("../assets/images/Profile/photo1.jpg"),
    icon: "call",
  },
  {
    id: 2,
    name: "Bahdon Abdi Soubaneh",
    text: "Yesterday,",
    time: "10:30",
    imagePath: require("../assets/images/Profile/photo2.jpg"),
    icon: "call",
  },
  {
    id: 3,
    name: "Hamza Abdi Soubaneh",
    text: "17 February,",
    time: "20:02",
    imagePath: require("../assets/images/Profile/photo3.jpg"),
    icon: "mic-outline",
  },
  {
    id: 4,
    name: "Hodan Abdi Soubaneh",
    text: "15 February,",
    time: "17:32",
    imagePath: require("../assets/images/Profile/photo4.jpg"),
    icon: "checkmark-done-outline",
  },
  {
    id: 5,
    name: "Macktireh Abdi Soubaneh",
    text: "Yesterday,",
    time: "10:02",
    imagePath: require("../assets/images/Profile/photo5.jpg"),
    icon: "checkmark-done-outline",
  },
  {
    id: 6,
    name: "Ismael Abdi Soubaneh",
    text: "10 February,",
    time: "00:02",
    imagePath: require("../assets/images/Profile/photo6.jpg"),
    icon: "checkmark-done-outline",
  },
  {
    id: 7,
    name: "Soumaya Abdi Soubaneh",
    text: "19 February,",
    time: "08:02",
    imagePath: require("../assets/images/Profile/photo7.jpg"),
    icon: "call",
  },
  {
    id: 8,
    name: "Ali Barkad",
    text: "8 January,",
    time: "18:15",
    imagePath: require("../assets/images/Profile/photo8.jpg"),
    icon: "mic-outline",
  },
  {
    id: 9,
    name: "Chady Osman",
    text: "18 January,",
    time: "20:02",
    imagePath: require("../assets/images/Profile/photo9.jpg"),
    icon: "checkmark-done-outline",
  },
  {
    id: 10,
    name: "Shamis Habane",
    text: "28 January,",
    time: "20:02",
    imagePath: require("../assets/images/Profile/photo10.jpg"),
    icon: "call",
  },
  {
    id: 11,
    name: "Shamis Habane",
    text: "28 January,",
    time: "20:02",
    imagePath: require("../assets/images/Profile/photo1.jpg"),
    icon: "call",
  },
  {
    id: 12,
    name: "Shamis Habane",
    text: "28 January,",
    time: "20:02",
    imagePath: require("../assets/images/Profile/photo2.jpg"),
    icon: "call",
  },
  {
    id: 13,
    name: "Shamis Habane",
    text: "28 January,",
    time: "20:02",
    imagePath: require("../assets/images/Profile/photo3.jpg"),
    icon: "call",
  },
  {
    id: 14,
    name: "Shamis Habane",
    text: "28 January,",
    time: "20:02",
    imagePath: require("../assets/images/Profile/photo4.jpg"),
    icon: "call",
  },
  {
    id: 15,
    name: "Shamis Habane",
    text: "28 January,",
    time: "20:02",
    imagePath: require("../assets/images/Profile/photo5.jpg"),
    icon: "call",
  },
];
export default callsInfo;
